#!/home/freeman/anaconda3/envs/aidds_web/bin/python
from tornado.wsgi import WSGIContainer
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop

from aidds_web import app_init
from aidds_web import web_args
from aidds_web.utils import app_exception
from aidds_web.utils import service_logs as logs

from aidds_web.restapi_server import app


def main(service_port=None):
    try:
        http_server = HTTPServer(WSGIContainer(app))
        http_server.listen(service_port)
        
        logs()
        logs(code='main', value=f'{service_port}/predict')
        logs(code='exit')
        logs()
        
        IOLoop.instance().start()
    except KeyboardInterrupt as _:
        print()
        logs(code='shut_down')
        exit()
        # raise app_exception(ke)
    except Exception as e:
        raise app_exception(e)


if __name__ == '__main__':
    try:
        app_init()
        args = web_args()
        main(service_port=args.port)
    except app_exception as ae:
        ae.print()
    except Exception as e:
        print(e)